services:
  - type: web
    name: gameday-stats
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn gameday_stats.wsgi"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: API_FOOTBALL_KEY
        sync: false
      - key: FOOTBALL_DATA_KEY
        sync: false