# Generated by Django 5.2.7 on 2025-10-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_team_abbreviation_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
