# Generated by Django 5.2.7 on 2025-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_team_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='api_id',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
