# Generated by Django 5.2.7 on 2025-10-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_alter_team_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player_stats',
            name='match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Player_Stats',
        ),
    ]
