# Generated by Django 5.2.7 on 2025-10-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_player_player_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='postion',
            new_name='position',
        ),
    ]
