# Generated by Django 5.2.5 on 2025-10-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_alter_player_name_alter_player_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='api_id',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
