# Generated by Django 5.2.5 on 2025-10-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_match_api_id_alter_team_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
