# Generated by Django 5.2.5 on 2025-10-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_alter_league_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
    ]
