# Generated by Django 5.2.7 on 2025-10-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_alter_team_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stats',
            name='player',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
