# Generated by Django 5.2.7 on 2025-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0022_player_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='api_id',
            new_name='api_id_football_api',
        ),
        migrations.AddField(
            model_name='team',
            name='api_id_football_data',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
