# Generated by Django 5.2.7 on 2025-10-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0024_remove_team_api_id_football_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_id_football_api',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
