# Generated by Django 5.2.7 on 2025-10-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_rename_api_id_football_id_league_api_id_football_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Play', 'In Play'), ('Finished', 'Finished'), ('Postponed', 'Postponed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=20),
        ),
    ]
