# Generated by Django 5.2.7 on 2025-10-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0030_alter_match_options_remove_match_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(null=True),
        ),
    ]
