# Generated by Django 5.2.7 on 2025-10-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_match_matchday'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='current_matchday',
            field=models.IntegerField(null=True),
        ),
    ]
