# Generated by Django 5.2.7 on 2025-10-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0037_remove_player_api_id_football_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='api_id_football_data',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
