# Generated by Django 5.2.7 on 2025-10-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0038_player_api_id_football_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player_stats',
            name='match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Player_Stats',
        ),
    ]
