# Generated by Django 5.2.7 on 2025-10-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0039_remove_player_stats_player_remove_player_stats_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('photo', models.URLField(null=True)),
                ('api_id_football_data', models.IntegerField(null=True, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='football.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='football.player')),
            ],
        ),
    ]
