# Generated by Django 5.2.7 on 2025-10-15 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0041_top_scorers_delete_player_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_scorers',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_top_scorer', to='football.league'),
        ),
    ]
