# Generated by Django 5.2.7 on 2025-10-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0043_alter_top_scorers_assists_alter_top_scorers_goals_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_Scorers',
        ),
    ]
