# Generated by Django 5.2.7 on 2025-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0047_top_scorers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='top_scorers',
            options={'ordering': ['league', '-goals']},
        ),
        migrations.AddField(
            model_name='team',
            name='club_colors',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='founded',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.CharField(null=True),
        ),
    ]
