# Generated by Django 5.2.7 on 2025-10-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0049_matchdetail_matchevent_matchplayer_teamstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='related_player',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='team',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamstatistic',
            name='match',
        ),
        migrations.RemoveField(
            model_name='teamstatistic',
            name='team',
        ),
        migrations.DeleteModel(
            name='MatchDetail',
        ),
        migrations.DeleteModel(
            name='MatchEvent',
        ),
        migrations.DeleteModel(
            name='MatchPlayer',
        ),
        migrations.DeleteModel(
            name='TeamStatistic',
        ),
    ]
