# Generated by Django 5.2.7 on 2025-10-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0053_match_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='total_matchdays',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
