# Generated by Django 5.2.5 on 2025-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0054_league_total_matchdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
