# Generated by Django 5.2.5 on 2025-10-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0055_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_scorers',
            name='assists',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='top_scorers',
            name='penalties',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
