# Generated by Django 5.2.5 on 2025-10-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0056_alter_top_scorers_assists_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_Scorers',
        ),
    ]
