# Generated by Django 5.2.5 on 2025-10-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0057_delete_top_scorers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Scorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0, null=True)),
                ('assists', models.IntegerField(blank=True, default=0, null=True)),
                ('penalties', models.IntegerField(blank=True, default=0, null=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_top_scorer', to='football.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='football.player')),
            ],
            options={
                'ordering': ['league', '-goals'],
            },
        ),
    ]
