# Generated by Django 5.2.7 on 2025-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_team_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
