# Generated by Django 5.2.7 on 2025-10-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
    ]
