# Generated by Django 5.2.7 on 2025-10-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_rename_postion_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
