# Generated by Django 5.2.5 on 2025-10-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_league_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='api_id',
            field=models.IntegerField(max_length=3, unique=True),
        ),
    ]
