# Generated by Django 5.2.7 on 2025-10-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_alter_player_age_alter_player_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goalsFor', models.IntegerField()),
                ('goalsAgainst', models.IntegerField()),
                ('goalDifference', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standing', to='football.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standing', to='football.team')),
            ],
        ),
    ]
