# Generated by Django 5.2.7 on 2025-10-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_alter_team_logo_standings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='api_id',
        ),
    ]
