# Generated by Django 5.2.7 on 2025-10-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_remove_team_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
