# Generated by Django 5.2.7 on 2025-10-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_team_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
