# Generated by Django 5.2.7 on 2025-10-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_remove_player_stats_player_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='football.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Player_Stats',
        ),
    ]
