# Generated by Django 5.2.7 on 2025-10-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_rename_api_id_team_api_id_football_api_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='api_id_football_api',
        ),
    ]
