# Generated by Django 5.2.7 on 2025-10-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_team_api_id_football_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='api_id_football_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
