# Generated by Django 5.2.7 on 2025-10-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_player_api_id_football_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
