# Generated by Django 5.2.7 on 2025-10-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0027_alter_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='api_id',
        ),
        migrations.AddField(
            model_name='league',
            name='api_id_football_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
