# Generated by Django 5.2.7 on 2025-10-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_remove_league_api_id_league_api_id_football_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='api_id_football_id',
            new_name='api_id_football_data',
        ),
    ]
