# Generated by Django 5.2.7 on 2025-10-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0033_team_coach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='coach',
            new_name='coach_name',
        ),
    ]
