# Generated by Django 5.2.7 on 2025-10-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0034_rename_coach_team_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.CharField(null=True),
        ),
    ]
