# Generated by Django 5.2.7 on 2025-10-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0035_team_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='api_id_football_id',
            new_name='api_id_football_data',
        ),
    ]
