# Generated by Django 5.2.7 on 2025-10-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0036_rename_api_id_football_id_player_api_id_football_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='api_id_football_data',
        ),
    ]
