# Generated by Django 5.2.7 on 2025-10-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0040_player_player_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Scorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('penalties', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='football.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Player_Stats',
        ),
    ]
