# Generated by Django 5.2.7 on 2025-10-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0042_top_scorers_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_scorers',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='top_scorers',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='top_scorers',
            name='penalties',
            field=models.IntegerField(null=True),
        ),
    ]
