# Generated by Django 5.2.7 on 2025-10-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0045_top_scorers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_Scorers',
        ),
    ]
