# Generated by Django 5.2.7 on 2025-10-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0050_remove_matchevent_match_remove_matchevent_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('referee', models.CharField(blank=True, max_length=255, null=True)),
                ('home_formation', models.CharField(blank=True, max_length=50, null=True)),
                ('away_formation', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='football.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow', 'Yellow Card'), ('red', 'Red Card'), ('substitution', 'Substitution')], max_length=20)),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('assist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('player_in', models.CharField(blank=True, max_length=100, null=True)),
                ('player_out', models.CharField(blank=True, max_length=100, null=True)),
                ('card', models.CharField(blank=True, max_length=20, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='football.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('is_starting', models.BooleanField(default=False)),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='football.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='football.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.PositiveIntegerField(blank=True, null=True)),
                ('corners', models.PositiveIntegerField(blank=True, null=True)),
                ('shots', models.PositiveIntegerField(blank=True, null=True)),
                ('shots_off_target', models.PositiveIntegerField(blank=True, null=True)),
                ('shots_on_target', models.PositiveIntegerField(blank=True, null=True)),
                ('yellow_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('red_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('saves', models.PositiveIntegerField(blank=True, null=True)),
                ('fouls', models.PositiveIntegerField(blank=True, null=True)),
                ('offsides', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='football.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='football.team')),
            ],
        ),
    ]
