# Generated by Django 5.2.7 on 2025-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0052_remove_matchevent_match_remove_matchevent_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
