name: ⚽ Update Matches

on:
  schedule:
    - cron: "0 * * * *"   # Every hour
  workflow_dispatch:

jobs:
  update_matches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run update_matches
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python manage.py update_matches