name: ⚽ Auto Update Football Data

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"          # update_matches (hourly)
    # Runs every 8 hours
    - cron: "0 */8 * * *"        # update_standings & update_top_scorers
    # Runs every 12 hours
    - cron: "0 */12 * * *"       # update_players, update_coaches, update_current_matchday
  workflow_dispatch:              # allows manual trigger

jobs:
  update_matches:
    if: github.event.schedule == '0 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update_matches command
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python manage.py update_matches


  update_standings_and_top_scorers:
    if: github.event.schedule == '0 */8 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update standings
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python manage.py update_standings
      - name: Update top scorers
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python manage.py update_top_scorers


  update_players_coaches_matchday:
    if: github.event.schedule == '0 */12 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update players
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python manage.py update_players
      - name: Update coaches
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python manage.py update_coaches
      - name: Update current matchday
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python manage.py update_current_matchday